# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish

on:
  push:
    tags:
      - '*'

env:
  itch_target: sirdorius/raylike-2025

jobs:
  build-wasm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish RayLikeWasm -c Release

    - name: Package as a zip
      working-directory: ./RayLikeWasm/bin/Debug/net8.0/browser-wasm/AppBundle
      run: |
        zip --recurse-paths ../${{ env.binary }}.zip .

    - name: Upload binaries to artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.binary }}.zip
        name: wasm
        retention-days: 1

  upload-to-itch:
    runs-on: ubuntu-latest
    needs:
      - build-wasm

    steps:
      # https://docs.github.com/en/actions/tutorials/store-and-share-data
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./builds

      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - name: Upload to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          ./butler push \
              --fix-permissions \
              --userversion="${{ steps.get_version.outputs.tag }}" \
              builds/index.zip \
              ${{ env.itch_target }}:wasm