# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish

on:
  workflow_dispatch:
    inputs:
      deploy_ref:
        description: 'ref to deploy'
        required: true
        default: 'main'
      dotnet_config:
        description: 'Config: Debug | Release'
        required: true
        type: choice
        default: Release
        options:
          - Debug
          - Release
      native_publish:
        description: 'Publish native versions'
        required: true
        type: boolean
        default: false

env:
  project_name: rl2025
  itch_target: sirdorius/rayguelike-2025

jobs:
  publish-wasm:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.deploy_ref }}
        lfs: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: RayLikeWasm/packages.lock.json
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools wasm-tools-net8
    - name: dotnet workload restore
      run: dotnet workload restore
    # needed for caching to work?
    # - name: dotnet restore
    #   run: dotnet restore --locked-mode
    - name: Publish
      run: dotnet publish RayLikeWasm -c ${{ github.event.inputs.dotnet_config }}

    - name: Package as a zip
      working-directory: RayLikeWasm/bin/${{ github.event.inputs.dotnet_config }}/net8.0/browser-wasm/AppBundle
      run: |
        zip --recurse-paths ${{ env.project_name }}-${{ github.sha }}.zip .
    - name: Install butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler -V
    - uses: olegtarasov/get-tag@v2.1.2
      id: get_version
    - name: Upload to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
      run: |
        ./butler push \
            --fix-permissions \
            --userversion="${{ steps.get_version.outputs.tag }}" \
            RayLikeWasm/bin/${{ github.event.inputs.dotnet_config }}/net8.0/browser-wasm/AppBundle/${{ env.project_name }}-${{ github.sha }}.zip \
            ${{ env.itch_target }}:wasm

  
  publish-native:
    if: ${{ github.event.inputs.native_publish }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.deploy_ref }}
        lfs: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: RayLikeWasm/packages.lock.json
    - name: dotnet workload restore
      run: dotnet workload restore
    - name: Publish
      run: dotnet publish RayLikeDesktop -c ${{ github.event.inputs.dotnet_config }} -r linux-x64 -p:PublishSingleFile=true

    - name: Package as a zip
      working-directory: RayLikeDesktop/bin/${{ github.event.inputs.dotnet_config }}/net9.0/linux-x64/publish
      run: |
        zip --recurse-paths ${{ env.project_name }}-${{ github.sha }}.zip .
    - name: Install butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler -V
    - uses: olegtarasov/get-tag@v2.1.2
      id: get_version
    - name: Upload to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
      run: |
        ./butler push \
            --fix-permissions \
            --userversion="${{ steps.get_version.outputs.tag }}" \
            RayLikeDesktop/bin/${{ github.event.inputs.dotnet_config }}/net9.0/linux-x64/publish/${{ env.project_name }}-${{ github.sha }}.zip \
            ${{ env.itch_target }}:linux-x64